name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo Hello, cruel world!

    - name: Run a multi-line script
      run: 
        echo 1.. 2.. 3..,
        echo Test started.
